services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    networks:
      - spring
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    networks:
      - spring
  app:
    build:
      context: .
    environment:
      ENV_PG_URL: jdbc:postgresql://postgres:5432/task_db
      ENV_PG_USERNAME: username
      ENV_PG_PASSWORD: password
      ENV_REDIS_HOST: redis
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
    networks:
      - spring
    volumes:
      - ./target:/app/target

networks:
  spring:
    driver: bridge