apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2025-05-18T15:48:28Z","generation":2,"name":"springtodo","namespace":"default","resourceVersion":"2305","uid":"c143c744-ef19-46c7-8047-bd71271e54f1"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"springtodo"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"springtodo"}},"spec":{"containers":[{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"docker"},{"name":"ENV_PG_USERNAME","valueFrom":{"secretKeyRef":{"key":"db-username","name":"springtodo-secret"}}},{"name":"ENV_PG_PASSWORD","valueFrom":{"secretKeyRef":{"key":"db-password","name":"springtodo-secret"}}},{"name":"ENV_PG_URL","valueFrom":{"configMapKeyRef":{"key":"db-url","name":"springtodo-config"}}}],"image":"kudzip/springtodo-app:latest","imagePullPolicy":"Always","name":"springtodo","ports":[{"containerPort":8082,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2025-05-18T15:48:28Z","lastUpdateTime":"2025-05-18T15:48:28Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2025-05-18T16:15:19Z","lastUpdateTime":"2025-05-18T16:15:19Z","message":"ReplicaSet \"springtodo-5994fb7666\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":2,"replicas":3,"unavailableReplicas":3,"updatedReplicas":1}}
  creationTimestamp: "2025-05-18T16:23:59Z"
  generation: 5
  name: springtodo
  namespace: default
  resourceVersion: "6289"
  uid: 081a617c-64a1-44d0-bb02-2853e232aee3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springtodo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-18T16:53:02Z"
      creationTimestamp: null
      labels:
        app: springtodo
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: ENV_PG_USERNAME
          valueFrom:
            secretKeyRef:
              key: db-username
              name: springtodo-secret
        - name: ENV_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: springtodo-secret
        - name: ENV_PG_URL
          valueFrom:
            configMapKeyRef:
              key: db-url
              name: springtodo-config
        image: kudzip/springtodo-app:latest
        imagePullPolicy: Always
        name: springtodo
        ports:
        - containerPort: 8082
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-05-18T16:53:08Z"
    lastUpdateTime: "2025-05-18T16:53:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-18T16:23:59Z"
    lastUpdateTime: "2025-05-18T16:53:08Z"
    message: ReplicaSet "springtodo-67c8564bbf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
